# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515d1b506004b1cf46a6ae69f68073c3702871dd13ea13ff7ce3ebd616ef68b707b3ca67f29cb225e8aad613abc5952d59800581a7599c52792e70ba33cce4f4

test:
  secret_key_base: 27e3853779cfa8568c9e0a8521b82a24baa207b628ce6f0bc736b6a92c1143473d1ce8c6f9bb8ad4d74a3a6833487d7b332fc4c95b4a5c95d021fd1374c05c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
